# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import tests.mockapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mockapp', '0002_mockperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockperson',
            name='birthdate',
            field=models.DateField(default=tests.mockapp.models.get_random_date, null=True),
        ),
    ]
