name: Test

on: [ pull_request, push ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        django-version: [ 2.2, 3.1, 3.2 ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
        elastic-version: [ 1.7, 2.4 ]
    services:
      elastic:
        image: elasticsearch:${{ matrix.elastic-version }}
        env:
          discovery.type: "single-node"
        options: >-
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
    #      solr:
    #        image: solr:6
    #        ports:
    #          - 9001:9001
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install system dependencies
        run: sudo apt install --no-install-recommends -y gdal-bin
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install coverage requests geopy tox
          pip install django==${{ matrix.django-version }} elasticsearch==${{ matrix.elastic-version }}
          python setup.py clean build install
      - name: Run test
        run: coverage run setup.py test
